# Wall sensor configuration
led_rise_time: 40 # [us]
rs_reference: 415
ls_reference: 332

rs_threshold: 200
rf_threshold: 50
lf_threshold: 400
ls_threshold: 130

# Battery
battery_correction_table:
 - [355, 5.0]
 - [688, 9.0]

# Gyro configuration
gyro_fir_coefficients:
- 1.0
# - -2.494829972812401e-18
# - -7.851195903558143e-03
# - 4.014735544403485e-02
# - -1.032535402203297e-01
# - 1.706609016841135e-01
# - 8.000000000000000e-01
# - 1.706609016841135e-01
# - -1.032535402203297e-01
# - 4.014735544403485e-02
# - -7.851195903558143e-03
# - -2.494829972812401e-18

gyro_correction_table: # binary raw value to rad/s
 - [-32768, -40.03366425054514]
 - [32767, 40.032442520068734]
gyro_correction_coefficient: 0.97

# Encoder configuration
enc_fir_coefficients:
 - 0.25
 - 0.25
 - 0.25
 - 0.25

# Hardware constants
wheel_diameter: 14.0 # [mm]
gear_ratio: 2.0


# Configuration for search run
# PID parameters
sr_omega_p: 4.0
sr_omega_i: 0.0
sr_omega_d: 1.0
sr_omega_i_limit: 0.0
sr_omega_dead_zone: 0.1

sr_position_x_p: 1000.0
sr_position_x_i: 1.0
sr_position_x_d: 300.0
sr_position_x_i_limit: 5.0
sr_position_x_dead_zone: 0.001

sr_velocity_p: 25.0
sr_velocity_i: 0.0
sr_velocity_d: 10.0
sr_velocity_i_limit: 0.0
sr_velocity_dead_zone: 0.0

sr_theta_p: 35.0
sr_theta_i: 4.0
sr_theta_d: 10.0
sr_theta_i_limit: 5.0
sr_theta_dead_zone: 0.0

sr_wall_p: 0.5
sr_wall_i: 0.0
sr_wall_d: 0.1
sr_wall_i_limit: 0.0
sr_wall_dead_zone: 0.0

sr_ff_rate: 0.0

# Speed parameters
sr_velocity: 0.25
sr_acceleration: 1.5
sr_deceleration: 1.5
