#!/usr/bin/env bash
esptool.py erase_flash
cargo fmt
cargo espflash flash --partition-table partitions.csv --baud 3000000
echo "Waiting for the device to reboot"
sleep 6
./script/ft ctrl_cfg.json ctrl_cfg.json
./script/cmd reset
#cargo espflash --partition-table partitions.csv $1 --monitor --speed 3000000
