#!/usr/bin/env python3

import serial
import sys
import time
import os

serial_port = '/dev/ttyUSB0'

dir_name = 'downloads/'

def receive_file(filename):
	ser = serial.Serial(serial_port, 921600, timeout=1)

	ser.write('\n'.encode('utf-8'))
	time.sleep(0.5)
	ser.readline()
	time.sleep(0.5)

	# Send dl command
	fullpath = "/sf/" + filename
	command = f"dl {fullpath}\n"
	print(command, end='')
	ser.write(command.encode('ascii'))

	# Receive file size
	file_size_str = ser.readline().decode('ascii').strip()
	print("filesize", file_size_str)
	file_size = int(file_size_str)

	# Download
	ser.write("\n".encode('ascii'))

	loop_count = file_size // 1024 + 1

	if not os.path.exists(dir_name):
		os.makedirs(dir_name)

	with open(dir_name + filename, 'wb') as f:
		total_read = 0
		print(f"Downloading {filename}...")
		for i in range(0, loop_count):
			read_size = min(1024, file_size - i * 1024)
			data = ser.read(read_size)
			f.write(data)
			total_read += len(data)

			# Print progress without newline
			print(f"\r{total_read}/{file_size}", end='')
	print("")

	ser.close()

if __name__ == "__main__":
	if len(sys.argv) != 2:
		print("Download a file from the micromouse")
		print("The file will be saved in the ./" + dir_name + " directory.")
		print("Usage: python dl {filename without /sf/}")
		sys.exit(1)

	filename = sys.argv[1]

	receive_file(filename)
